### PR TITLE
combined post and comment scanner into 1 and added discord webhook support

### LINKED ISSUE #10: Add Webhooks on Trigger
A simply discord/slack webhook to alert admins of spam

### PR DESCRIPTION
**Pull request by lvanrem**
Not sure if this is something you guys wanted, but was bored so I thought I would just combine the two "resolve report" functions together into one. 

Haven't been able to extensively test it.

Closes #10

### CODE REVIEW

**Comment by lvanrem** [comment]
(also very nice project, might try to get this running on lemmy.world)

**Comment by db0** [comment]
Heh that works :D. I'm always up for some nice deduplication. I'll test and merge later

**Comment by lvanrem** [comment]
Saw this and thought that I would add it. Accidentilly did so on this branch, but oh well... #10

**Comment by poVoq** [comment]
Support for Slack like webhooks should be similar and would allow sending notifications to IRC, XMPP and I think also Matrix. Would be a nice addition.

**Comment by lvanrem** [comment]
@poVoq almost done with that, will do a pull request for that in a few hours.

**Pull request merged**
